--테이블 삭제
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE CATEGORIES CASCADE CONSTRAINTS;
DROP TABLE PRODUCTS CASCADE CONSTRAINTS;
DROP TABLE INVENTORIES CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE ORDER_ITEMS CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEES CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_STOCKS CASCADE CONSTRAINTS;

--시퀀스 삭제
DROP SEQUENCE USERS_SEQ;
DROP SEQUENCE PRODUCTS_SEQ;
DROP SEQUENCE INVENTORIES_SEQ;
DROP SEQUENCE EMPLOYEES_SEQ;
DROP SEQUENCE CATEGORIES_SEQ;
DROP SEQUENCE ORDERS_SEQ;
DROP SEQUENCE PRODUCT_STOCKS_SEQ;

----------------테이블-----------------
--사용자 테이블
CREATE TABLE USERS(
    ID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30) NOT NULL,
    PASSWORD VARCHAR2(30) NOT NULL, 
    JUMIN VARCHAR2(15) NOT NULL, 
    PHONE VARCHAR2(15) NOT NULL, 
    EMAIL VARCHAR2(40), 
    AGREE_WT CHAR(1) NOT NULL, 
    ADMIN_AT CHAR(1) NOT NULL, 
    SIGNUP_DATE TIMESTAMP NOT NULL);
    

--카테고리 테이블
CREATE TABLE CATEGORIES(
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL);
    

--제품 정보 테이블
CREATE TABLE PRODUCTS(
    ID NUMBER PRIMARY KEY,
    CATEGORY_ID NUMBER NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    PRICE NUMBER(10) NOT NULL,
    INGREDIENT VARCHAR2(60) NOT NULL,
    QUANTITY VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_PRODUCTS_CATEGORIES
    FOREIGN KEY(CATEGORY_ID)
    REFERENCES CATEGORIES(ID)
    ON DELETE CASCADE);


--제품 수량 테이블 
CREATE TABLE INVENTORIES (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    STOCK NUMBER NOT NULL,
    UNIT VARCHAR2(5) NOT NULL
    );
        
        
--주문번호 테이블
CREATE TABLE ORDERS (
    ID NUMBER PRIMARY KEY, 
    ORDER_DATE TIMESTAMP NOT NULL);
    
    
--주문 내역 테이블
CREATE TABLE ORDER_ITEMS (
    ORDERS_ID NUMBER,
    ITEM_ID NUMBER,
    PRODUCTS_ID NUMBER NOT NULL,
    QUANTITY NUMBER(10) NOT NULL,
    UNIT_PRICE NUMBER(10) NOT NULL,
    CONSTRAINT PK_ORDER_ITEMS
        PRIMARY KEY(ORDERS_ID, ITEM_ID),
    CONSTRAINT FK_ORDER_ITEMS_ORDERS
        FOREIGN KEY(ORDERS_ID)
        REFERENCES ORDERS(ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_ORDER_ITEMS_PROUDCTS
        FOREIGN KEY(PRODUCTS_ID)
        REFERENCES PRODUCTS(ID)
        ON DELETE CASCADE);
        
--직원관리 테이블        
CREATE TABLE EMPLOYEES (
	ID NUMBER PRIMARY KEY,
	NAME VARCHAR2(15) NOT NULL,
	JUMIN VARCHAR2(15) NOT NULL,
	PHONE VARCHAR2(15) NOT NULL,
	HIRE_DATE DATE NOT NULL);
    
--판매관리 테이블
CREATE TABLE PRODUCT_STOCKS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,    
    INPUT_STOCK NUMBER(10) NOT NULL,
    OUTPUT_STOCK NUMBER(10) NOT NULL,
    CURRENT_STOCK NUMBER(10) NOT NULL);
    
 
---------------시퀀스------------------

CREATE SEQUENCE ORDERS_SEQ
START WITH 1 INCREMENT BY 1;


CREATE SEQUENCE CATEGORIES_SEQ
START WITH 1 INCREMENT BY 1;

    
CREATE SEQUENCE PRODUCTS_SEQ
START WITH 1 INCREMENT BY 1;

    
CREATE SEQUENCE INVENTORIES_SEQ
START WITH 1 INCREMENT BY 1;


CREATE SEQUENCE EMPLOYEES_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE PRODUCT_STOCKS_SEQ
START WITH 1 INCREMENT BY 1;
    


------테스트 데이터---------
--CATEGORIES 테이블
INSERT INTO CATEGORIES VALUES (CATEGORIES_SEQ.NEXTVAL, '햄버거');
INSERT INTO CATEGORIES VALUES (CATEGORIES_SEQ.NEXTVAL, '감자튀김');
INSERT INTO CATEGORIES VALUES (CATEGORIES_SEQ.NEXTVAL, '커피');
INSERT INTO CATEGORIES VALUES (CATEGORIES_SEQ.NEXTVAL, '음료');

--Inventories 테이블
INSERT INTO INVENTORIES VALUES (INVENTORIES_SEQ.NEXTVAL, '양상추', 50, 'kg');
INSERT INTO INVENTORIES VALUES (INVENTORIES_SEQ.NEXTVAL, '토마토', 70, 'kg');
INSERT INTO INVENTORIES VALUES (INVENTORIES_SEQ.NEXTVAL, '빵', 700, '개');
INSERT INTO INVENTORIES VALUES (INVENTORIES_SEQ.NEXTVAL, '불고기패티', 50, 'kg');
INSERT INTO INVENTORIES VALUES (INVENTORIES_SEQ.NEXTVAL, '머스타드소스', 20, 'L');
INSERT INTO INVENTORIES VALUES (INVENTORIES_SEQ.NEXTVAL, '케냐원두', 20, 'kg');
INSERT INTO INVENTORIES VALUES (INVENTORIES_SEQ.NEXTVAL, '소고기패티', 50, 'kg');
INSERT INTO INVENTORIES VALUES (INVENTORIES_SEQ.NEXTVAL, '우유', 50, 'L');
INSERT INTO INVENTORIES VALUES (INVENTORIES_SEQ.NEXTVAL, '양상추', 50, 'kg');
INSERT INTO INVENTORIES VALUES (INVENTORIES_SEQ.NEXTVAL, '콜라', 200, 'L');


--PRODUCKS 테이블
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 1, '불고기버거', 3900, '빵, 불고기패티, 양상추, 소스, 토마토', '2, 1, 50, 5, 30');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 1, '새우버거', 3900, '빵, 쉬림프패티, 양상추, 소스, 토마토', '2, 1, 50, 5, 30');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 1, '데리버거', 2500, '빵, 기본패티, 양상추, 소스, 토마토', '2, 1, 50, 5, 30');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 1, '치킨버거', 2900, '빵, 치킨조각, 양상추, 소스, 토마토', '2, 1, 50, 5, 30');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 1, '더블X2', 5500, '빵, 고기패티, 양상추, 소스, 토마토', '2, 2, 50, 5, 30');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 1, 'T-Rex', 3700, '빵, 맛있는패티, 양상추, 소스, 토마토', '2, 1, 50, 5, 30');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 1, '한우불고기', 7000, '빵, 소고기패티, 양상추, 소스, 토마토', '2, 1, 50, 5, 30');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 1, 'AZ버거', 6600, '빵, AZ패티, 양상추, 소스, 토마토', '2, 1, 50, 5, 30');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 1, '핫크리스피버거', 4900, '빵, 매운치킨, 양상추, 소스, 토마토', '2, 1, 50, 5, 30');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 1, '클래식 치즈버거', 4400, '빵, 모짜렐라패티, 양상추, 소스, 토마토', '2, 1, 50, 5, 30');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 2, '포테이토', 1500, '감자튀김, 소금', '50, 3');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 2, '어니언 양념감자', 2000, '감자튀김, 어니언양념', '45, 1');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 2, '칠리 양념감자', 2000, '감자튀김, 칠리양념', '45, 1');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 2, '치즈 양념감자', 2000, '감자튀김, 치즈양념', '45, 1');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 3, '아메리카노', 2500, '케냐원두', '10');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 3, '카페라떼', 3500, '케냐원두, 우유', '10, 50');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 4, '핫초코', 2000, '우유, 코코아', '20, 3');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 4, '아이스티', 2200, '아이스티팩', '1');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 4, '오렌지주스', 2500, '오렌지', '0.5');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 4, '콜라', 1700, '콜라', '30');
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 4, '사이다', 1700, '사이다', '30');





--employees 테이블
INSERT INTO EMPLOYEES VALUES (EMPLOYEES_SEQ.NEXTVAL, '홍길동', '000912-3057896', '010-6666-7777', '20-05-17');
INSERT INTO EMPLOYEES VALUES (EMPLOYEES_SEQ.NEXTVAL, '임꺽정', '010418-1365489', '010-3333-1685', '19-03-03');
INSERT INTO EMPLOYEES VALUES (EMPLOYEES_SEQ.NEXTVAL, '박영주', '051231-1478563', '010-5648-7453', '18-02-01');
INSERT INTO EMPLOYEES VALUES (EMPLOYEES_SEQ.NEXTVAL, '이원재', '030127-3368451', '010-3218-7789', '20-01-23');
INSERT INTO EMPLOYEES VALUES (EMPLOYEES_SEQ.NEXTVAL, '이원모', '000824-3741563', '010-4622-8954', '20-02-27');
INSERT INTO EMPLOYEES VALUES (EMPLOYEES_SEQ.NEXTVAL, '최주호', '951203-1004789', '010-8954-5254', '20-03-12');

--상품재고테이블
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '불고기버거', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '새우버거', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '데리버거', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '치킨버거', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , 'T-REX', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '한우불고기', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , 'AZ버거', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '더블X2', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '모짜렐라 인 더 버거', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '핫크리스피버거', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '클래식 치즈버거', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '포테이토', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '어니언 양념감자', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '칠리 양념감자', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '치즈 양념감자', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '아메리카노', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '카페라떼', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '카푸치노', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '카라멜 마끼아또', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '핫초코', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '아이스티', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '오렌지주스', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '콜라', 200, 0, 200);
INSERT INTO PRODUCT_STOCKS VALUES (PRODUCT_STOCKS_SEQ.NEXTVAL , '사이다', 200, 0, 200);


--상품재고 트리거
create or replace trigger autoUpdateStock
    after insert on order_items
    for each row
declare
    oi_id order_items.products_id%type;
    oi_quan order_items.quantity%type;
begin
    oi_id := :new.products_id;
    oi_quan := :new.quantity;
    update Product_Stocks
        set current_stock = current_stock - oi_quan,
            output_stock = output_stock + oi_quan
    where Product_Stocks.id = oi_id;
    end;
/



--select regexp_substr('SMITH,ALLEN,WARD,JONES,PKY,BAKER','[^,]+', 1, level) from dual
--connect by regexp_substr('SMITH,ALLEN,WARD,JONES,PKY,BAKER', '[^,]+', 1, level) is not null;
